'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Logo } from '@/components/Logo'
import {
  Building2,
  Truck,
  User,
  ScanLine,
  ArrowLeft,
  Shield,
  BarChart3,
  ChevronDown,
  ChevronUp,
} from 'lucide-react'
import {
  BrokerDashboardPreview,
  BrokerMyLoadsPreview,
  BrokerCarrierLiveMapPreview,
  CarrierDashboardPreview,
  CarrierFleetPreview,
  DriverAppPreview,
  DriverQRPreview,
  DriverQRDisplayPreview,
  DriverVerifiedPreview,
  ShipperGateLoadEntryPreview,
  ShipperGatePreview,
  ShipperSuccessPreview,
} from '@/components/investors/RolePreviews'

const ROLES = [
  {
    id: 'broker',
    title: 'Broker',
    icon: Building2,
    description: 'Post loads, receive bids from carriers, assign loads, and track verification. Load Board and My Loads (BOL, driver location). Enter a load number to see a live map of the driver assigned to that load. Shipper scans the driver’s QR at the dock—brokers see verification status.',
    viewLabel: 'Broker dashboard — Load Board, My Loads (incl. live driver map), Fleet',
  },
  {
    id: 'carrier',
    title: 'Carrier',
    icon: Truck,
    description: 'View assigned loads, manage fleet and drivers, bid on broker loads. Enter a load number to see a live map of the driver on that load. Same dashboard with carrier-scoped data and driver assignment.',
    viewLabel: 'Carrier dashboard — My Loads (incl. live driver map), Fleet',
  },
  {
    id: 'driver',
    title: 'Driver',
    icon: User,
    description: 'Mobile-friendly driver app: view assigned load, show IronGate QR at the dock (one-time, 15 min). The QR can only be generated by the driver on the carrier’s platform that booked the load, when they are at the dock (geofence).',
    viewLabel: 'Driver app — Load details, IronGate QR, verification steps',
  },
  {
    id: 'shipper',
    title: 'Shipper',
    icon: ScanLine,
    description: 'Gate verification: enter load number, scan the driver’s QR with the device camera. Instant confirmation of correct driver and carrier before releasing freight.',
    viewLabel: 'Shipper Gate — Load lookup, QR scan, verified result',
  },
] as const

const INVESTOR_VIDEO_URL = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_INVESTOR_VIDEO_URL : ''
const LOCAL_VIDEO_PATH = '/videos/investor-overview.mp4'

function InvestorVideo() {
  const isEmbed = INVESTOR_VIDEO_URL && /^https?:\/\//i.test(INVESTOR_VIDEO_URL)
  const hasLocal = !!INVESTOR_VIDEO_URL && !isEmbed

  if (isEmbed) {
    return (
      <div className="mt-4 aspect-video w-full overflow-hidden rounded-xl border border-iron-700 bg-black">
        <iframe
          title="Product overview video"
          src={INVESTOR_VIDEO_URL}
          className="h-full w-full"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        />
      </div>
    )
  }

  const videoSrc = hasLocal ? INVESTOR_VIDEO_URL : LOCAL_VIDEO_PATH
  return (
    <div className="mt-4 aspect-video w-full overflow-hidden rounded-xl border border-iron-700 bg-black">
      <video
        className="h-full w-full object-contain"
        src={videoSrc}
        controls
        playsInline
        preload="metadata"
      >
        <track kind="captions" />
      </video>
    </div>
  )
}

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false)
  return (
    <li className="rounded-lg border border-divider bg-surface/50 overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center justify-between gap-4 px-4 py-3 text-left text-sm font-medium text-[#F9FAFB] hover:bg-white/5 transition-colors"
        aria-expanded={open}
      >
        <span>{question}</span>
        {open ? <ChevronUp className="h-4 w-4 shrink-0 text-primary" /> : <ChevronDown className="h-4 w-4 shrink-0 text-primary" />}
      </button>
      {open && (
        <div className="border-t border-divider px-4 py-3 text-sm text-[#A3A3A3] leading-relaxed bg-background/50">
          {answer}
        </div>
      )}
    </li>
  )
}

export default function InvestorsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-10 border-b border-divider bg-surface/95 backdrop-blur">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3 sm:px-6">
          <Link href="/" className="inline-flex">
            <Logo className="text-white" />
          </Link>
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-[#A3A3A3] hover:text-[#F9FAFB]"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6 sm:py-16">
        {/* Hero */}
        <section className="flex flex-col items-center sm:flex-row sm:items-start sm:justify-center sm:gap-8">
          <img
            src="/icons/icon-192.png"
            alt=""
            width={192}
            height={192}
            className="h-32 w-32 shrink-0 object-contain opacity-95 sm:h-40 sm:w-40 md:h-48 md:w-48"
            decoding="async"
          />
          <div className="text-center sm:text-left mt-4 sm:mt-0">
            <p className="font-display text-sm font-semibold uppercase tracking-wider text-primary">
              For Investors
            </p>
            <h1 className="mt-3 font-display text-3xl font-bold tracking-tight text-[#F9FAFB] sm:text-4xl">
              See the platform
            </h1>
            <p className="mx-auto mt-4 max-w-2xl text-lg leading-relaxed text-[#A3A3A3] sm:mx-0">
              IronFreight is a B2B freight verification platform. Brokers, carriers, drivers, and shippers each have a dedicated experience inside the same product. Below is how each role uses the actual site.
            </p>
          </div>
        </section>
        <section className="mt-8 flex flex-col items-center text-center">
          <div className="w-full max-w-2xl rounded-xl border border-primary/30 bg-primary/5 px-4 py-4 text-left">
            <p className="text-sm font-medium text-primary">Key: IronGate QR</p>
            <p className="mt-1 text-sm text-[#A3A3A3] leading-relaxed">
              The QR code can only be generated by the driver on the carrier’s platform that booked the load, when they are at the dock (geofence). The shipper then scans it to verify the correct driver and carrier before releasing freight.
            </p>
          </div>
          <div className="mt-6 flex flex-wrap items-center justify-center gap-4">
            <div className="flex items-center gap-2 rounded-lg border border-divider bg-surface px-4 py-2 text-sm text-[#A3A3A3]">
              <Shield className="h-4 w-4 text-primary" />
              Verify carrier, confirm driver, protect freight
            </div>
            <div className="flex items-center gap-2 rounded-lg border border-divider bg-surface px-4 py-2 text-sm text-[#A3A3A3]">
              <BarChart3 className="h-4 w-4 text-primary" />
              Built for the future of freight
            </div>
          </div>
        </section>

        {/* Video: public/videos/investor-overview.mp4 or NEXT_PUBLIC_INVESTOR_VIDEO_URL */}
        <section className="mt-14">
          <h2 className="font-display text-xl font-bold text-[#F9FAFB] sm:text-2xl">
            Product overview
          </h2>
          <InvestorVideo />
        </section>

        {/* By role */}
        <section className="mt-16">
          <h2 className="font-display text-xl font-bold text-[#F9FAFB] sm:text-2xl">
            Experience by role
          </h2>
          <p className="mt-2 text-sm text-[#A3A3A3]">
            Live UI from the app — the same screens each role sees when they sign in.
          </p>

          <ul className="mt-10 space-y-16">
            {ROLES.map((role) => {
              const Icon = role.icon
              return (
                <li key={role.id} id={role.id}>
                  <div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:gap-10">
                    <div className="flex-shrink-0">
                      <div className="flex h-14 w-14 items-center justify-center rounded-xl border border-primary/30 bg-primary/10">
                        <Icon className="h-7 w-7 text-primary" />
                      </div>
                    </div>
                    <div className="min-w-0 flex-1">
                      <h3 className="font-display text-lg font-bold text-[#F9FAFB]">
                        {role.title}
                      </h3>
                      <p className="mt-2 text-sm leading-relaxed text-[#A3A3A3]">
                        {role.description}
                      </p>
                      <p className="mt-3 text-xs font-medium text-[#737373]">
                        {role.viewLabel}
                      </p>
                      <div className="mt-6">
                        <p className="mb-4 text-xs font-medium text-iron-500">Actual app screens — what this role sees</p>
                        {role.id === 'broker' && (
                          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Load Board — post & manage loads</p><BrokerDashboardPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">My Loads — track, BOL, driver location</p><BrokerMyLoadsPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Track driver — enter load number, live map</p><BrokerCarrierLiveMapPreview role="broker" /></div>
                          </div>
                        )}
                        {role.id === 'carrier' && (
                          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">My Loads — assigned loads</p><CarrierDashboardPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Fleet — invite drivers, CDL verification</p><CarrierFleetPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Track driver — enter load number, live map</p><BrokerCarrierLiveMapPreview role="carrier" /></div>
                          </div>
                        )}
                        {role.id === 'driver' && (
                          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Assigned load — pickup & delivery</p><DriverAppPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">QR ready — wait for shipper, then show</p><DriverQRPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">QR displayed — 15 min, single-use</p><DriverQRDisplayPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Verified — after shipper scans</p><DriverVerifiedPreview /></div>
                          </div>
                        )}
                        {role.id === 'shipper' && (
                          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Step 1 — Enter load number</p><ShipperGateLoadEntryPreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Step 2 — Expected driver/carrier, scan QR</p><ShipperGatePreview /></div>
                            <div><p className="mb-1.5 text-[11px] font-medium text-iron-400">Success — Driver & carrier verified</p><ShipperSuccessPreview /></div>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </li>
              )
            })}
          </ul>
        </section>

        {/* FAQ */}
        <section className="mt-20">
          <h2 className="font-display text-xl font-bold text-[#F9FAFB] sm:text-2xl">
            Frequently asked questions
          </h2>
          <ul className="mt-6 space-y-3">
            {[
              {
                q: 'What problem are you solving and how big is it?',
                a: 'We’re tackling double brokering, identity fraud, and cargo theft in freight. Brokers and shippers often don’t know if the carrier and driver showing up are who they contracted. We verify the real carrier, confirm driver identity at the dock, and prove chain of custody—so the right party is verified before freight is released. The market is large and the pain is acute for anyone moving high-value or time-sensitive freight.',
              },
              {
                q: 'How does the verification actually work at the dock?',
                a: 'The driver (on the carrier’s platform that booked the load) generates a single-use IronGate QR only when they’re at the dock—within the geofence. The shipper enters the load number, sees who’s expected, then scans the driver’s QR with their device. We confirm it’s the right driver and carrier and record the verification. No QR can be generated by anyone else or for a load that carrier didn’t book.',
              },
              {
                q: 'Can brokers and carriers see where their drivers are?',
                a: 'Yes. Both can enter a load number in My Loads and see a live map of the driver assigned to that load—including pickup/delivery geofences and the driver’s position when they have the app open. That visibility is built into the same dashboard they use for loads and fleet.',
              },
              {
                q: 'Who are your customers and how do you charge?',
                a: 'Our customers are brokers, carriers, shippers, and drivers—each with a role in the same platform. We use subscription and usage-based pricing: brokers and carriers pay for the platform; we charge for IronGate verification events (per verified load); shippers may pay per location or per scan. Exact pricing is on the main site and we’re happy to walk through it.',
              },
              {
                q: 'What’s your defensibility?',
                a: 'We’re building the verification layer that ties carrier identity, driver identity, and custody to the load. That means integrated geofencing, QR and token logic, and audit trail—not a bolt-on. As more brokers and shippers require verification, the network effect and switching cost increase. We’re also focused on compliance and chain-of-custody evidence that matters in claims and disputes.',
              },
              {
                q: 'What are you raising for and what’s the use of funds?',
                a: 'We’re focused on product, distribution, and operations so we can scale verification across more loads and customers. For specific round details and use of funds, we’d prefer to discuss directly—reach out via the contact below.',
              },
            ].map((item, index) => (
              <FAQItem key={index} question={item.q} answer={item.a} />
            ))}
          </ul>
        </section>

        {/* CTA */}
        <section className="mt-20 rounded-2xl border border-primary/20 bg-primary/5 px-6 py-10 text-center sm:px-10">
          <h2 className="font-display text-lg font-bold text-[#F9FAFB]">
            Interested in learning more?
          </h2>
          <p className="mt-2 text-sm text-[#A3A3A3]">
            For investor inquiries and product demos, reach out.
          </p>
          <a
            href="mailto:Info@getironfreight.com?subject=Investor%20inquiry"
            className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 font-medium text-black hover:bg-primary/90"
          >
            Contact — Info@getironfreight.com
          </a>
        </section>
      </main>
    </div>
  )
}
